/**
 * Downloads the three display faces used by the interface as self-hosted
 * variable woff2 files and writes the matching `@font-face` stylesheet.
 *
 * The specification forbids a remote font request at runtime, so the files are
 * fetched once, committed under `public/fonts/`, and served from the same
 * origin as everything else. Only the `latin` and `latin-ext` subsets are kept:
 * the catalog's search metadata is English-only, and emoji glyphs always come
 * from the operating system rather than from a bundled face.
 *
 * Run with `npm run generate:fonts`. Output is committed, so a normal build
 * never reaches the network.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const FONT_DIR = resolve(HERE, '../public/fonts');
const STYLESHEET = resolve(HERE, '../src/fonts.css');

/** Google's CSS endpoint returns woff2 only when it believes the client supports it. */
const MODERN_BROWSER_UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

/** The two subsets that cover the interface copy; everything else is dropped. */
const SUBSETS = ['latin', 'latin-ext'];

const FAMILIES = [
  {
    family: 'Bricolage Grotesque',
    slug: 'bricolage-grotesque',
    query: 'Bricolage+Grotesque:opsz,wght@12..96,200..800',
    weightRange: '200 800',
    usage: 'display headings, stat numbers, tile info affordance',
  },
  {
    family: 'Plus Jakarta Sans',
    slug: 'plus-jakarta-sans',
    query: 'Plus+Jakarta+Sans:wght@200..800',
    weightRange: '200 800',
    usage: 'every piece of interface and body text',
  },
  {
    family: 'JetBrains Mono',
    slug: 'jetbrains-mono',
    query: 'JetBrains+Mono:wght@100..800',
    weightRange: '100 800',
    usage: 'counts, code points, keycaps',
  },
];

const FACE_BLOCK = /@font-face\s*\{([^}]*)\}/g;

function readDeclaration(block, property) {
  const match = new RegExp(`${property}:\\s*([^;]+);`).exec(block);
  return match ? match[1].trim() : undefined;
}

/**
 * Google emits one `@font-face` per subset, each preceded by a `/* subset *\/`
 * comment. The comment is the only reliable subset marker, so the raw CSS is
 * split on it before the blocks are parsed.
 */
function parseFaces(css) {
  const faces = [];
  for (const segment of css.split('/*').slice(1)) {
    const subset = segment.slice(0, segment.indexOf('*/')).trim();
    if (!SUBSETS.includes(subset)) continue;
    FACE_BLOCK.lastIndex = 0;
    const block = FACE_BLOCK.exec(segment);
    if (!block) continue;
    const source = readDeclaration(block[1], 'src');
    const unicodeRange = readDeclaration(block[1], 'unicode-range');
    const url = source && /url\((https:[^)]+)\)/.exec(source)?.[1];
    if (!url || !unicodeRange) continue;
    faces.push({ subset, url, unicodeRange });
  }
  return faces;
}

async function fetchText(url) {
  const response = await fetch(url, { headers: { 'user-agent': MODERN_BROWSER_UA } });
  if (!response.ok) throw new Error(`${url} responded ${response.status}`);
  return response.text();
}

async function fetchBinary(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url} responded ${response.status}`);
  return Buffer.from(await response.arrayBuffer());
}

async function main() {
  mkdirSync(FONT_DIR, { recursive: true });

  const rules = [];
  let totalBytes = 0;

  for (const definition of FAMILIES) {
    const css = await fetchText(
      `https://fonts.googleapis.com/css2?family=${definition.query}&display=swap`,
    );
    const faces = parseFaces(css);
    if (faces.length !== SUBSETS.length) {
      throw new Error(
        `${definition.family}: expected ${SUBSETS.length} subsets, found ${faces.length}`,
      );
    }

    for (const face of faces) {
      const fileName = `${definition.slug}-${face.subset}.woff2`;
      const bytes = await fetchBinary(face.url);
      writeFileSync(resolve(FONT_DIR, fileName), bytes);
      totalBytes += bytes.byteLength;
      rules.push(
        [
          `/* ${definition.family} — ${face.subset} · ${definition.usage} */`,
          '@font-face {',
          `  font-family: '${definition.family}';`,
          '  font-style: normal;',
          `  font-weight: ${definition.weightRange};`,
          '  font-display: swap;',
          `  src: url('/fonts/${fileName}') format('woff2');`,
          `  unicode-range: ${face.unicodeRange};`,
          '}',
        ].join('\n'),
      );
      process.stdout.write(
        `${fileName.padEnd(38)} ${(bytes.byteLength / 1024).toFixed(1)} KB\n`,
      );
    }
  }

  writeFileSync(
    STYLESHEET,
    [
      '/*',
      ' * Generated by scripts/generate-fonts.mjs — do not edit by hand.',
      ' *',
      ' * Self-hosted so the running app never issues a third-party font request.',
      ' * Re-run `npm run generate:fonts` after changing the family list.',
      ' */',
      '',
      ...rules,
      '',
    ].join('\n'),
  );

  process.stdout.write(
    `\nWrote ${rules.length} faces (${(totalBytes / 1024).toFixed(1)} KB) and src/fonts.css\n`,
  );
}

await main();
